name: Run Python Scripts Daily
on:
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 2:30 AM UTC
  workflow_dispatch:  # Allows manual triggering
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install airstack
          pip install aiohttp --only-binary :all:
      
      - name: Run cBTC.py
        run: python cBTC.py
